### ISSUE TITLE
Active page indicator on pagination

### ISSUE THREAD

**Issue by varunk29** [swve/framestack#15]
Its a bit hard to keep track of the current page number

![image](https://user-images.githubusercontent.com/42642511/130331987-0c4ca7f9-747c-457a-9933-432cee4dcb6b.png)

**Comment by swve** [comment]
Hi @varunk29 👋🏻, 

Thanks for the proposition, it is true that with no active page indicator its hard visually to keep track, 

I'll try to fix that as soon as possible, PR will be linked to this Issue 

Thanks!

**Comment by swve** [comment]
![image](https://user-images.githubusercontent.com/29493708/132945184-17e090e2-1fc6-41c7-bbe6-2c014d2bc3ff.png)

 It is now easier to track page number, 
Thanks for hunting this issue @varunk29
